<div class="wrapper">

	<header class="header">
		<a class="brand" href="/">Shagtv.net</a>
		<?= $this->elements->getMenu(); ?>
	</header><!-- .header-->

	<div class="middle">
		<div class="container">
			<main class="content">
				<?= $this->getContent(); ?>
			</main><!-- .content -->
		</div><!-- .container-->
		<!--aside class="left-sidebar">
			<?= $this->elements->getTabs(); ?>
		</aside--><!-- .left-sidebar -->
	</div><!-- .middle-->
</div><!-- .wrapper -->

<footer class="footer">
	<p>&copy; <a href="/">Shagtv.net</a> 2014</p>
</footer><!-- .footer -->