<?= $this->getContent(); ?>

<div class="page-header">
    <h1>Редактирование видео</h1>
</div>

<form class="backend-video-form" method="POST">
	<input type="hidden" name="id" id="id" value="<?= $video->id; ?>">
	<fieldset>
		<div>
			<label for="name"><strong>Название</strong></label>
			<input type="text" name="name" id="name" value="<?= $video->name; ?>" title="Введите название видео">
		</div>
		<div>
			<label for="code"><strong>Код</strong></label>
			<input type="text" name="code" id="code" value="<?= $video->code; ?>" title="Введите код видео">
		</div>
		<div>
			<label for="descr"><strong>Описание</strong></label>
			<textarea name="descr" id="descr" title="Введите описание видео"><?= $video->descr; ?></textarea>
		</div>
		<div>
			<label for="tags"><strong>Теги</strong></label>
			<input type="text" name="tags" id="tags" value="<?= $video->tags; ?>" title="Введите теги видео">
		</div>
	</fieldset>
	<input type="submit" value="Отправить"/>
</form>