<?= $this->getContent(); ?>

<div class="page-header">
    <h1>Редактирование видео</h1>
</div>

<form class="backend-video-form" method="POST">
	<input type="hidden" name="id" id="id" value="<?= $video->id; ?>">
	<fieldset>
		<div>
			<label for="name"><strong>Название</strong></label>
			<input type="text" name="name" id="name" value="<?= $video->name; ?>" title="Введите название видео">
		</div>
		<div>
			<label for="code"><strong>Код</strong></label>
			<textarea name="code" id="code" title="Вставьте код видео"><?= $video->code; ?></textarea>
		</div>
		<div>
			<label for="descr"><strong>Описание</strong></label>
			<textarea name="descr" id="descr" title="Введите описание видео"><?= $video->descr; ?></textarea>
		</div>
	</fieldset>
	<input type="submit" value="Отправить"/>
</form>