<?= $this->getContent(); ?>

<div class="page-header">
    <h1>Видео</h1>
</div>

<table class="width-table">
	<tr>
		<th>Название</th>
		<th></th>
	</tr>
	<?php foreach ($videos as $video): ?>
		<tr>
			<td><?= $video->name; ?></td>
			<td>
				<a href="/backend/video/edit/<?= $video->id; ?>">edit</a>
				<a href="/backend/video/delete/<?= $video->id; ?>">delete</a>
			</td>
		</tr>
	<?php endforeach; ?>
</table>