<?= $this->getContent(); ?>

<div class="page-header">
    <h1>Свяжитесь со мной</h1>
</div>

<p>Пишите вопросы или заявки на сотрудничество.</p>

<form action="/contact/send" method="POST" id="contact-form">
	<fieldset>
		<div>
			<label for="name"><strong>Имя:</strong></label>
			<input id="name" name="name" title="Введите Ваше имя."/>
		</div>
		<div>
			<label for="email"><strong>Email:</strong></label>
			<input id="email" name="email" title="Введите адрес электронной почты."/>
		</div>
		<div>
			<label for="comments"><strong>Сообщение:</strong></label>
			<textarea id="comments" rows="6" name="comments" title="Напишите сообщение."></textarea>
		</div>
	</fieldset>
	<input type="submit" value="Отправить"/>
</form>