<div class="page-header">
    <h1>Timestamp to Date/time конвертер</h1>
</div>

<div id="timestamp-converter-wrap">
	<table>
		<tr>
			<td>
				<input type="text" name="timestamp" id="timestamp" value="" placeholder="Unix timestamp">
			</td>
		</tr>
		<tr>
			<td>
				<input type="button" value="Конвертировать" id="timestamp-converter">
				<input type="button" value="Очистить" id="timestamp-reset">
			</td>
		</tr>
		<tr>
			<td>
				<input type="text" name="datetime" id="datetime" value="" placeholder="Date/time" disabled>
			</td>
		</tr>
	</table>
</div>