<div class="page-header">
    <h1>Видео: <?= $tag; ?></h1>
</div>

<?php if (!empty($videos)): ?>
	<?php foreach ($videos as $video): ?>
		<div class="page-header">
			<a href="/index/view/<?= $video->id; ?>"><h2><?= $video->name; ?></h2></a>
		</div>

		<div>
			<a class="fancybox" href="http://img.youtube.com/vi/<?= $video->code; ?>/maxresdefault.jpg">
				<img alt="<?= $video->name; ?>" title="<?= $video->name; ?>" src="http://img.youtube.com/vi/<?= $video->code; ?>/0.jpg">
			</a>
		</div>

		<div><?= $video->descr; ?></div>

		<div>Загружено; <?= $video->created_at; ?></div>
		<hr>

	<?php endforeach; ?>
<?php else: ?>		
		<div>Видео не найдено</div>
<?php endif; ?>