<!DOCTYPE html>
<html lang="ru">
	<head>
		<meta charset="utf-8" />
		<?= $this->tag->getTitle(); ?>
		<meta name="keywords" content="<?= $keywords; ?>"/>
		<meta name="description" content="<?= $description; ?>"/>
		<link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css" />
		<link rel="stylesheet" type="text/css" href="/js/fb/jquery.fancybox.css" media="screen" />
		<link rel="stylesheet" href="/css/style.css" type="text/css"/>
	</head>
	<body>
		<?= $this->getContent(); ?>
		<script src="/js/jquery.min.js"></script>
		<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
		<script type="text/javascript" src="/js/fb/jquery.fancybox.pack.js"></script>
		<script src="/js/script.min.js"></script>
		<!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
	</body>
</html>