<table class="table table-hover">
	<tr>
		<th>id</th>
		<th>login</th>
		<th>password</th>
		<th></th>
	</tr>
	<?php foreach ($users as $user): ?>
	<tr>
		<td><?= $user->id; ?></td>
		<td><?= $user->login; ?></td>
		<td><?= $user->password; ?></td>
		<td>
			<a href="/user/edit/<?= $user->login; ?>">edit</a>
			<a href="/user/delete/<?= $user->login; ?>">delete</a>
		</td>
	</tr>
	<?php endforeach; ?>
</table>