<!DOCTYPE html>
<html lang="ru">
	<head>
		<meta charset="utf-8" />
		<?php echo $this->tag->getTitle() ?>
		<meta name="keywords" content=""/>
		<meta name="description" content=""/>
		<link rel="stylesheet" href="/css/style.css" type="text/css"/>
	</head>
	<body>
		<?= $this->getContent(); ?>
		<script src="/js/jquery.min.js"></script>
		<script src="/js/script.js"></script>
		<!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
	</body>
</html>