<!DOCTYPE html>
<html lang="ru">
	<head>
		<meta charset="utf-8" />
		<?= $this->tag->getTitle(); ?>
		<meta name="keywords" content="<?= $keywords; ?>"/>
		<meta name="description" content="<?= $description; ?>"/>
		<link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css" />
		<link rel="stylesheet" type="text/css" href="/js/fb/jquery.fancybox.css" media="screen" />
		<link rel="stylesheet" href="/css/style.min.css" type="text/css"/>
	</head>
	<body>
		<?= $this->getContent(); ?>
		<script src="/js/jquery.min.js"></script>
		<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
		<script type="text/javascript" src="/js/fb/jquery.fancybox.pack.js"></script>
		<script src="/js/script.min.js"></script>
		<!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
		<script type="text/javascript">

			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-48203314-1']);
			_gaq.push(['_trackPageview']);

			(function() {
				var ga = document.createElement('script');
				ga.type = 'text/javascript';
				ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0];
				s.parentNode.insertBefore(ga, s);
			})();

		</script>
		<!-- Yandex.Metrika informer -->
		<a href="https://metrika.yandex.ru/stat/?id=24223291&amp;from=informer"
		   target="_blank" rel="nofollow"><img src="//bs.yandex.ru/informer/24223291/3_1_FFFFFFFF_EFEFEFFF_0_pageviews"
											style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" onclick="try {
					Ya.Metrika.informer({i: this, id: 24223291, lang: 'ru'});
					return false
				} catch (e) {
				}"/></a>
		<!-- /Yandex.Metrika informer -->

		<!-- Yandex.Metrika counter -->
		<script type="text/javascript">
			(function(d, w, c) {
				(w[c] = w[c] || []).push(function() {
					try {
						w.yaCounter24223291 = new Ya.Metrika({id: 24223291,
							webvisor: true,
							clickmap: true,
							trackLinks: true,
							accurateTrackBounce: true});
					} catch (e) {
					}
				});

				var n = d.getElementsByTagName("script")[0],
						s = d.createElement("script"),
						f = function() {
							n.parentNode.insertBefore(s, n);
						};
				s.type = "text/javascript";
				s.async = true;
				s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

				if (w.opera == "[object Opera]") {
					d.addEventListener("DOMContentLoaded", f, false);
				} else {
					f();
				}
			})(document, window, "yandex_metrika_callbacks");
		</script>
		<noscript><div><img src="//mc.yandex.ru/watch/24223291" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
		<!-- /Yandex.Metrika counter -->
	</body>
</html>