<!DOCTYPE html>
<html lang="ru">
	<head>
		<meta charset="utf-8"/>
		<!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1' /><![endif]-->
		<meta name="viewport" content="width=device-width, initial-scale=1"/>
		<?php echo $this->tag->getTitle() ?>

		<link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css"/>	

		<!--link rel="stylesheet" href="/bootstrap/css/bootstrap-responsive.min.css"/-->
		<link rel="stylesheet" href="/css/style.css" type="text/css"/>
	</head>
	<body style>
		<?= $this->getContent(); ?>
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
		
		<!--script src="/js/jquery.min.js"></script-->
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
		<script src="/bootstrap/js/bootstrap.min.js"></script>
		<!--script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script-->
		

		<!--link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css" />
		<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script-->
		<script type="text/javascript"  src="/js/script.js"></script>
		<script type="text/javascript">

			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-48203314-1']);
			_gaq.push(['_trackPageview']);

			(function() {
			  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();

		</script>
	</body>
</html>
