<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="/">Shagtv.net</a>
			<?= $this->elements->getMenu(); ?>
        </div>
    </div>
</div>

<div class="container">
    <div class="page-content">
		<?= $this->getContent(); ?>
    </div>
	<hr>
    <footer>
        <p>&copy; <a href="/">Shagtv.net</a> 2014</p>
    </footer>
</div>